### ISSUE TITLE
Error running Wechaty Redux with Ducks 

### ISSUE THREAD

**Issue by sbis04** [wechaty/docusaurus#1043]
I tried running the example present [here](https://github.com/wechaty/wechaty-redux/blob/master/examples/ducks-proposal.ts) but it gave me some errors.

This is the code I tried to run:

```ts
import { Wechaty } from 'wechaty'
import { Ducks } from 'ducks'
import {
    WechatyRedux,
    Duck,
} from 'wechaty-redux'

/**
 * 1. Ducksify Wechaty Redux API
 */
const ducks = new Ducks({ wechaty: Duck })
const store = ducks.configureStore()

/**
 * 2. Instantiate Wechaty with Redux Plugin
 */
const bot = Wechaty.instance({ puppet: 'wechaty-puppet-whatsapp' })
bot.use(WechatyRedux({ store }))

/**
 * 3. Using Redux Store with Wechaty Ducks API!
 *  (With the Power of Ducks / Ducksify)
 */
const wechatyDuck = ducks.ducksify('wechaty')

store.subscribe(() => console.info(store.getState()))
wechatyDuck.operations.ding(bot.id, 'Ducksify Style ding!')
```

I have attached the error output below.

<details><summary>Terminal logs are here</summary>
<p>

```sh
> wechaty-ducks@1.0.0 start
> ts-node src/ducks-bot.ts

08:50:12 INFO Config registering process.on("unhandledRejection") for development/debug
08:50:12 VERB Config constructor()
08:50:13 VERB Wechaty constructor()
08:50:13 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
08:50:13 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
08:50:13 VERB WechatyRedux ({"store":{}})
08:50:13 VERB WechatyRedux WechatyReduxPlugin(Wechaty#ckqx79mrm0000ho0a42835mqm<wechaty-puppet-wechat>())
08:50:13 VERB WechatyRedux install(store, Wechaty#ckqx79mrm0000ho0a42835mqm<wechaty-puppet-wechat>())
08:50:13 VERB Wechaty on(puppet, listener) registering... listenerCount: 0
{ ducks: { wechaty: {} } }
08:50:13 ERR Config ###########################
08:50:13 ERR Config uncaughtException: Error: no wechaty found for id ckqx79mrm0000ho0a42835mqm
    at Object.getWechaty (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/src/manager.ts:27:11)
    at MergeMapSubscriber.ding$ [as project] (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/src/duck/rx-async.ts:37:3)
    at MergeMapSubscriber._tryNext (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/mergeMap.ts:131:21)
    at MergeMapSubscriber._next (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/mergeMap.ts:121:12)
    at MergeMapSubscriber.Subscriber.next (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at QueueAction.<anonymous> (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/operators/observeOn.ts:62:71)
    at QueueAction.AsyncAction._execute (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:116:12)
    at QueueAction.execute (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/scheduler/QueueAction.ts:26:12)
    at QueueScheduler.AsyncScheduler.flush (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:39:27)
    at QueueAction.schedule (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/scheduler/QueueAction.ts:19:20)
    at QueueScheduler.Scheduler.schedule (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/Scheduler.ts:60:56)
    at /Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/operators/observeOn.ts:62:45
    at OperatorSubscriber._this._next (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:43:13)
    at OperatorSubscriber.Subscriber.next (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/Subject.ts:63:20
    at Object.errorContext (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Subject.next (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/rxjs/src/internal/Subject.ts:58:5)
    at /Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/redux-observable/dist/cjs/createEpicMiddleware.js:53:32
    at /Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/wechaty-redux/src/duck/operations.ts:24:76
    at Object.ding (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/ducks/src/bundle.ts:157:12)
    at Object.<anonymous> (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/src/ducks-bot.ts:27:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/ts-node/src/bin.ts:330:12)
    at Object.<anonymous> (/Users/souvikbiswas/Programming/Docs/wechaty-ducks/node_modules/ts-node/src/bin.ts:477:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 uncaughtException
08:50:13 ERR Config ###########################
```

</p>
</details>

**Comment by sbis04** [comment]
Can any mentor (@huan or @lijiarui) please help me solve this error?

**Comment by huan** [comment]
Hi @sbis04 ,

Thank you very much for reporting this bug!

I believe I have just fixed it by the latest commit that linked to this issue, please try again, and let me know if it works or not.

## The fix code

```diff
const wechatyDuck = ducks.ducksify('wechaty')
+ await bot.start()
```

**Comment by sbis04** [comment]
Thanks @huan, this fixed the issue with ducks proposal style of redux.
