### ISSUE TITLE
Error running wechaty with vanilla redux

### ISSUE THREAD

**Issue by shwetalsoni** [wechaty/docusaurus#1044]
I tried running the example present [here](https://github.com/wechaty/wechaty-redux/blob/master/examples/vanilla-redux.ts) but it showed some errors.
The code is given below:

```ts

 import {
  createStore,
  applyMiddleware,
}                         from 'redux'
import {
  createEpicMiddleware,
  combineEpics,
}                         from 'redux-observable'
import { Wechaty }        from 'wechaty'
import {
  WechatyRedux,
  Duck,
}                         from 'wechaty-redux'  

/**
 * 1. Configure Store with RxJS Epic Middleware for Wechaty Ducks API
 */
const epicMiddleware = createEpicMiddleware()

const store = createStore(
  Duck.default,
  applyMiddleware(epicMiddleware),
)

const rootEpic = combineEpics(...Object.values(Duck.epics))
epicMiddleware.run(rootEpic)

/**
 * 2. Instantiate Wechaty and Install Redux Plugin
 */
const bot = Wechaty.instance({ puppet: 'wechaty-puppet-mock' })
bot.use(WechatyRedux({ store }))

/**
 * 3. Using Redux Store with Wechaty Ducks API!
 */
store.subscribe(() => console.info(store.getState()))

store.dispatch(Duck.actions.ding(bot.id, 'dispatch a ding action'))
// The above code 👆 is exactly do the same thing with the following code 👇 :
Duck.operations.ding(store.dispatch)(bot.id, 'call ding from operations')

```

Error output is attached below.

<details><summary>Terminal logs</summary>
<p>

```sh

12:40:02 INFO Config registering process.on("unhandledRejection") for development/debug
12:40:02 VERB Config constructor()
12:40:03 VERB Wechaty constructor()
12:40:03 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
12:40:03 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
12:40:03 VERB WechatyRedux ({"store":{}})
12:40:03 VERB WechatyRedux WechatyReduxPlugin(Wechaty#ckqxfh7sq0000k80q0lot3xur<wechaty-puppet-mock>())
12:40:03 VERB WechatyRedux install(store, Wechaty#ckqxfh7sq0000k80q0lot3xur<wechaty-puppet-mock>())
12:40:03 VERB Wechaty on(puppet, listener) registering... listenerCount: 0
{}
{}
12:40:04 ERR Config ###########################
12:40:04 ERR Config uncaughtException: Error: no wechaty found for id ckqxfh7sq0000k80q0lot3xur
    at Object.getWechaty (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/src/manager.ts:27:11)
    at MergeMapSubscriber.ding$ [as project] (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/src/duck/rx-async.ts:37:3)
    at MergeMapSubscriber._tryNext (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/mergeMap.ts:131:21)
    at MergeMapSubscriber._next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/mergeMap.ts:121:12)
    at MergeMapSubscriber.Subscriber.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at QueueAction.<anonymous> (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/operators/observeOn.ts:62:71)
    at QueueAction.AsyncAction._execute (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:116:12)
    at QueueAction.execute (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/QueueAction.ts:26:12)
    at QueueScheduler.AsyncScheduler.flush (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:39:27)
    at QueueAction.schedule (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/QueueAction.ts:19:20)
    at QueueScheduler.Scheduler.schedule (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Scheduler.ts:60:56)
    at /home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/operators/observeOn.ts:62:45
    at OperatorSubscriber._this._next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:43:13)
    at OperatorSubscriber.Subscriber.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Subject.ts:63:20
    at Object.errorContext (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Subject.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Subject.ts:58:5)
    at Object.dispatch (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/redux-observable/dist/cjs/createEpicMiddleware.js:53:32)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/vanilla-redux/src/vanilla-redux.ts:39:7)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:330:12)
    at Object.<anonymous> (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:477:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 uncaughtException
12:40:04 ERR Config ###########################
Error: no wechaty found for id ckqxfh7sq0000k80q0lot3xur
    at Object.getWechaty (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/src/manager.ts:27:11)
    at MergeMapSubscriber.ding$ [as project] (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/src/duck/rx-async.ts:37:3)
    at MergeMapSubscriber._tryNext (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/mergeMap.ts:131:21)
    at MergeMapSubscriber._next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/mergeMap.ts:121:12)
    at MergeMapSubscriber.Subscriber.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at FilterSubscriber._next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/operators/filter.ts:101:24)
    at FilterSubscriber.Subscriber.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/wechaty-redux/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at QueueAction.<anonymous> (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/operators/observeOn.ts:62:71)
    at QueueAction.AsyncAction._execute (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:116:12)
    at QueueAction.execute (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/QueueAction.ts:26:12)
    at QueueScheduler.AsyncScheduler.flush (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:39:27)
    at QueueAction.schedule (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/scheduler/QueueAction.ts:19:20)
    at QueueScheduler.Scheduler.schedule (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Scheduler.ts:60:56)
    at /home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/operators/observeOn.ts:62:45
    at OperatorSubscriber._this._next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:43:13)
    at OperatorSubscriber.Subscriber.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Subject.ts:63:20
    at Object.errorContext (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at Subject.next (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/rxjs/src/internal/Subject.ts:58:5)
    at Object.dispatch (/home/shwetal/Desktop/WECHATY/vanilla-redux/node_modules/redux-observable/dist/cjs/createEpicMiddleware.js:53:32)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/vanilla-redux/src/vanilla-redux.ts:39:7)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:330:12)
    at Object.<anonymous> (/home/shwetal/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/bin.ts:477:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path /home/shwetal/Desktop/WECHATY/vanilla-redux
npm ERR! command failed
npm ERR! command sh -c ts-node "src/vanilla-redux.ts"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shwetal/.npm/_logs/2021-07-10T07_10_04_127Z-debug.log

```
</p>
</details>

**Comment by huan** [comment]
Dear @shwetalsoni ,

I believe my reply at https://github.com/wechaty/wechaty.js.org/issues/1043#issuecomment-882236714 can help you solve the problem.

Please let me know if it help you fix your problem or not, thanks!

**Comment by sbis04** [comment]
I guess the vanilla redux code (present in [examples](https://github.com/wechaty/wechaty-redux/blob/master/examples/vanilla-redux.ts)) needs a bit of refactoring because it's not inside an `async` block. It worked with the following updated code:

```ts
import {
    createStore,
    applyMiddleware,
} from 'redux'
import {
    createEpicMiddleware,
    combineEpics,
} from 'redux-observable'
import { Wechaty } from 'wechaty'
import {
    WechatyRedux,
    Duck,
} from 'wechaty-redux'

async function main() {
    /**
    * 1. Configure Store with RxJS Epic Middleware for Wechaty Ducks API
    */
    const epicMiddleware = createEpicMiddleware()

    const store = createStore(
        Duck.default,
        applyMiddleware(epicMiddleware),
    )

    const rootEpic = combineEpics(...Object.values(Duck.epics))
    epicMiddleware.run(rootEpic)

    /**
     * 2. Instantiate Wechaty and Install Redux Plugin
     */
    const bot = Wechaty.instance({ puppet: 'wechaty-puppet-mock' })
    bot.use(WechatyRedux({ store }))
    await bot.start()

    /**
     * 3. Using Redux Store with Wechaty Ducks API!
     */
    store.subscribe(() => console.info(store.getState()))

    store.dispatch(Duck.actions.ding(bot.id, 'dispatch a ding action'))
}

main()
    .catch(console.error)
```

@haun but I got confused in one part, why is the vanilla redux also using the Ducks API?

**Comment by huan** [comment]
@sbis04 Thanks for pointing the problem out, I believe your code is correct, it would be great if you can send a PR to fix that example.

For your question: the "vanilla" in this example means using the vanilla "createStore" from the "redux" instead of using "ducks.configureStore()". 

The `Ducks` package providing some helper utility functions to simplify the code, such as "configureStore()".

**Comment by sbis04** [comment]
@huan I have sent a PR for this to the `wechaty-redux` repo: https://github.com/wechaty/wechaty-redux/pull/29

**Comment by huan** [comment]
That's great, PR merged.

Please keep the spaces before the `from` after the `import` in the future because that's the style of the Wechaty, thank you very much!

**Comment by sbis04** [comment]
Thanks @huan, okay I will keep in mind from next time.
