### ISSUE TITLE
Error on running room bot with wechaty-puppet-whatsapp

### ISSUE THREAD

**Issue by shwetalsoni** [wechaty/docusaurus#1119]
There is a problem that I'm encountering when running **room bot** and **busy bot** with `wechaty-puppet-whatsapp`.
It is working fine with other puppets like `wechaty-puppet-wecht4u` and `wechaty-puppet-mock`.

I have attached the terminal logs below:

<details><summary>Terminal logs</summary>
<p>

```sh

12:23:24 VERB MemoryCard constructor({"name":"room-bot","multiplex":{"name":"puppet","parent":{"options":{"name":"room-bot"},"name":"room-bot","payload":{},"multiplexNameList":[],"storage":{"name":"room-bot","options":{"type":"file"},"absFileName":"/home/shwetal/Desktop/WECHATY/room-bot/room-bot.memory-card.json"}}}})
12:23:24 VERB PuppetManager resolve({puppet: wechaty-puppet-whatsapp, puppetOptions: undefined})
12:23:24 VERB PuppetManager resolveName(wechaty-puppet-whatsapp)
12:23:24 VERB PuppetManager checkModule(wechaty-puppet-whatsapp)
/home/shwetal/Desktop/WECHATY/room-bot/node_modules/node-webpmux/webp.js:441
  #convertToExtended() {
                    ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/whatsapp-web.js/src/util/Util.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/whatsapp-web.js/src/Client.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/whatsapp-web.js/index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty-puppet-whatsapp/src/whatsapp.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty-puppet-whatsapp/src/puppet-whatsapp.ts:52:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty-puppet-whatsapp/src/mod.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty/src/puppet-manager.ts:136:26
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Function.resolveName (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty/src/puppet-manager.ts:136:26)
    at Function.resolve (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty/src/puppet-manager.ts:88:24)
    at Wechaty.initPuppet (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty/src/wechaty.ts:401:28)
    at Wechaty.start (/home/shwetal/Desktop/WECHATY/room-bot/node_modules/wechaty/src/wechaty.ts:725:7)
12:23:26 ERR Wechaty start() exception: Unexpected token '('
12:23:26 INFO Bot error: SyntaxError: Unexpected token '('
12:23:26 VERB Wechaty <wechaty-puppet-whatsapp> stop() v0.62.3 is stopping ...
12:23:26 VERB StateSwitch <WechatyReady> off(true) <- (true)
12:23:26 VERB StateSwitch <Wechaty> off(pending) <- (false)
12:23:26 WARN Wechaty stop() puppet.stop() exception: Cannot read property 'stop' of undefined
12:23:26 VERB StateSwitch <Wechaty> off(true) <- (pending)

```
</p>
</details>

Can any mentor @huan or @lijiarui  help me with this?

**Comment by lijiarui** [comment]
Hi @shwetalsoni  Could you provide the reproduce code and step for this log?
