### ISSUE TITLE
Error running the shell-bot

### ISSUE THREAD

**Issue by sbis04** [wechaty/docusaurus#1145]
I was trying to run [shell-bot](https://github.com/wechaty/wechaty-getting-started/blob/main/examples/advanced/shell-bot.ts) locally using the command ` ts-node examples/advanced/shell-bot.ts` but it produces the following error:

```ts
/Users/souvikbiswas/Programming/Docs/test-wechaty/wechaty-getting-started/node_modules/ts-node/src/index.ts:618
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
examples/advanced/shell-bot.ts:15:17 - error TS4111: Property 'wechaty' comes from an index signature, so it must be accessed with ['wechaty'].

15   shell.context.wechaty = wechaty
                   ~~~~~~~

    at createTSError (/Users/souvikbiswas/Programming/Docs/test-wechaty/wechaty-getting-started/node_modules/ts-node/src/index.ts:618:12)
    at reportTSError (/Users/souvikbiswas/Programming/Docs/test-wechaty/wechaty-getting-started/node_modules/ts-node/src/index.ts:622:19)
    at getOutput (/Users/souvikbiswas/Programming/Docs/test-wechaty/wechaty-getting-started/node_modules/ts-node/src/index.ts:809:36)
    at Object.compile (/Users/souvikbiswas/Programming/Docs/test-wechaty/wechaty-getting-started/node_modules/ts-node/src/index.ts:1111:30)
    at Module.m._compile (/Users/souvikbiswas/Programming/Docs/test-wechaty/wechaty-getting-started/node_modules/ts-node/src/index.ts:1224:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/souvikbiswas/Programming/Docs/test-wechaty/wechaty-getting-started/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

Can any of the mentors (@lijiarui or @huan) help me solve this issue?

**Comment by huan** [comment]
I believe that it would be convenient to just ignore this example for now because it's too simple. Please skip it.

**Comment by sbis04** [comment]
Okay, thanks for the suggestion @huan
