### ISSUE TITLE
Broken links testing

### ISSUE THREAD

**Issue by abhishek-iiit** [wechaty/docusaurus#1291]
## Steps I followed :
1. `git clone` my wechaty.org repo with the latest pull
2.  ran the command `npm install` and then `npm test`
3. got the error for which logs can be found below

any help would be appreciated and Thankyou in advance

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test:unit' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'pretest:unit', 'test:unit', 'posttest:unit' ]
5 info lifecycle wechaty.js.org@0.9.22~pretest:unit: wechaty.js.org@0.9.22
6 info lifecycle wechaty.js.org@0.9.22~test:unit: wechaty.js.org@0.9.22
7 verbose lifecycle wechaty.js.org@0.9.22~test:unit: unsafe-perm in lifecycle true
8 verbose lifecycle wechaty.js.org@0.9.22~test:unit: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/manne/Desktop/Github/wechaty.js.org/node_modules/.bin:/usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/manne/Desktop/Github/wechaty.js.org/node_modules/.bin:/home/manne/anaconda3/bin:/home/manne/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle wechaty.js.org@0.9.22~test:unit: CWD: /home/manne/Desktop/Github/wechaty.js.org
10 silly lifecycle wechaty.js.org@0.9.22~test:unit: Args: [ '-c',
10 silly lifecycle   'ts-node --files ./node_modules/.bin/blue-tape \'src/**/*.spec.ts\' \'tests/**/*.spec.ts\'' ]
11 silly lifecycle wechaty.js.org@0.9.22~test:unit: Returned: code: 1  signal: null
12 info lifecycle wechaty.js.org@0.9.22~test:unit: Failed to exec test:unit script
13 verbose stack Error: wechaty.js.org@0.9.22 test:unit: `ts-node --files ./node_modules/.bin/blue-tape 'src/**/*.spec.ts' 'tests/**/*.spec.ts'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid wechaty.js.org@0.9.22
15 verbose cwd /home/manne/Desktop/Github/wechaty.js.org
16 verbose Linux 5.11.0-34-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test:unit"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error wechaty.js.org@0.9.22 test:unit: `ts-node --files ./node_modules/.bin/blue-tape 'src/**/*.spec.ts' 'tests/**/*.spec.ts'`
22 error Exit status 1
23 error Failed at the wechaty.js.org@0.9.22 test:unit script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by Rohitesh-Kumar-Jain** [comment]
I am unable to figure out the error, is anyone else having the same issue?

**Comment by Rohitesh-Kumar-Jain** [comment]
Can you pls share the full text, I mean from the npm test till the end, then I may or may not be able to figure out the cause  😅

**Comment by abhishek-iiit** [comment]
![Screenshot from 2021-09-13 23-25-22](https://user-images.githubusercontent.com/69477761/133133024-e1008470-9da0-499d-bc97-416366819165.png)

I got this after running `npm test` to my master branch

**Comment by abhishek-iiit** [comment]
### Reinstalled nodejs v14
Got fix with the command : 
```ts
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Now, closing this Issue :)

**Comment by Rohitesh-Kumar-Jain** [comment]
great 🎉
