### ISSUE TITLE
npm run test, `Error: Cannot find module 'react'`

### ISSUE THREAD

**Issue by lijiarui** [wechaty/docusaurus#1379]
I have runned `npm install` and `npx browserslist@latest --update-db` as the terminal requested.

Then when I run `npm run test`, it has the following error on wechaty server (lijiarui@dev.chatie.io), it has the following error:

```shell
lijiarui@wechaty-contributors:~/wechaty.js.org$ npm run test

> wechaty.js.org@0.10.27 test
> npm-run-all lint test:unit


> wechaty.js.org@0.10.27 lint
> npm-run-all lint:es lint:ts lint:md lint:fn lint:yml


> wechaty.js.org@0.10.27 lint:es
> eslint "src/**/*.ts" "tests/**/*.spec.ts" --ignore-pattern tests/fixtures/


> wechaty.js.org@0.10.27 lint:ts
> tsc --isolatedModules --noEmit


> wechaty.js.org@0.10.27 lint:md
> markdownlint --ignore _site/ --ignore node_modules/ --ignore docusaurus/node_modules/ "**/*.md"


> wechaty.js.org@0.10.27 lint:fn
> file-name-linter .file-name-linter.json

 🏁  Finished linting jekyll/_posts
 👀  Ignoring jekyll/assets/css
 👀  Ignoring jekyll/assets/images
 👀  Ignoring jekyll/assets/js
 👀  Ignoring jekyll/assets/contributors/wechaty
 🏁  Finished linting jekyll/assets

> wechaty.js.org@0.10.27 lint:yml
> true || yamllint jekyll/_data/*.yml


> wechaty.js.org@0.10.27 test:unit
> cross-env TAP_TIMEOUT=60 NODE_OPTIONS="--no-warnings --loader=ts-node/esm" tap "src/**/*.spec.ts" "tests/**/*.spec.ts"

Error: Cannot find module 'react'
Require stack:
- /home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/treport/lib/index.js
- /home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/import-jsx/index.js
- /home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/treport/index.js
- /home/lijiarui/wechaty.js.org/node_modules/tap/bin/run.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/treport/lib/index.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/home/lijiarui/wechaty.js.org/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.replacementCompile (/home/lijiarui/wechaty.js.org/node_modules/append-transform/index.js:60:13)
    at Module.module._compile (/home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/import-jsx/index.js:45:11)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/treport/lib/index.js',
    '/home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/import-jsx/index.js',
    '/home/lijiarui/wechaty.js.org/node_modules/tap/node_modules/treport/index.js',
    '/home/lijiarui/wechaty.js.org/node_modules/tap/bin/run.js'
  ]
}
TAP version 13
1..0
# time=2.895ms
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
ERROR: "test:unit" exited with 1.
```

**Comment by huan** [comment]
It seems that the GitHub Actions works without any problem, so I believe this issue is related to your local environment?
