### ISSUE TITLE
[bug] test:unit crash in windows

### ISSUE THREAD

**Issue by jihuayu** [wechaty/docusaurus#344]
应该是 ts-node --file 这个参数有点问题，我在 powershell, git bash, wsl 下运行全部报错。 

```log
> ts-node --files ./node_modules/.bin/blue-tape 'src/**/*.spec.ts' 'tests/**/*.spec.ts'

C:\Users\jihuayu\Documents\.soc\111\node_modules\.bin\blue-tape:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at main (C:\Users\jihuayu\Documents\.soc\111\node_modules\ts-node\src\bin.ts:227:14)
    at Object.<anonymous> (C:\Users\jihuayu\Documents\.soc\111\node_modules\ts-node\src\bin.ts:513:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechaty.github.io@0.2.27 test:unit: `ts-node --files ./node_modules/.bin/blue-tape 'src/**/*.spec.ts' 'tests/**/*.spec.ts'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechaty.github.io@0.2.27 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jihuayu\scoop\persist\nodejs\cache\_logs\2020-07-19T15_18_55_306Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by huan** [comment]
Good catch! 

A PR to fix it will be welcome.
