### ISSUE TITLE
`block in materialize': Could not find public_suffix-4.0.6 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by huan** [wechaty/docusaurus#685]
We run into this issue of a sudden for no reason, because everything works yesterday.

```
bundle exec jekyll build
/var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find public_suffix-4.0.6 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/spec_set.rb:82:in `map!'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/spec_set.rb:82:in `materialize'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/definition.rb:170:in `specs'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/definition.rb:240:in `specs_for'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/definition.rb:222:in `requested_specs'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/runtime.rb:20:in `setup'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler.rb:148:in `setup'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/ui/shell.rb:136:in `with_level'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/ui/shell.rb:88:in `silence'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.13/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
make: *** [Makefile:26: build] Error 1
Error: Process completed with exit code 2.
```

It seems that remove the `bundle config path ~/.npm/bundle` to disable cache will solve this problem.

**Comment by huan** [comment]
It seems this issue has gone after remove the cache.
